.github/workflows/go.yml, .github/workflows/golangci-lint.yml
https://github.com/golangci/golangci-lint-action
=> Add golangci-lint-action GitHub Action

bits/bits.go, bits/bits_benchmark_test.go, bits/bits_test.go, examples/initcreator/main.go, mp4/aac.go, mp4/box.go, mp4/esds.go, mp4/file.go, mp4/initsegment.go, mp4/mdia.go, mp4/mediasegment.go, mp4/smhd.go, mp4/stsd.go
Can now generate both AVC and HEVC init and media segments.
=> Fixed generation of media segments for both video and audio

README.md, examples/resegmenter/resegment.go, mp4/audiosamplentry.go, mp4/box.go, mp4/container.go, mp4/dinf.go, mp4/dref.go, mp4/edts.go, mp4/file.go, mp4/fragment.go, mp4/initsegment.go, mp4/initsegment_test.go, mp4/mdia.go, mp4/minf.go, mp4/moof.go, mp4/moov.go, mp4/mvex.go, mp4/stbl.go, mp4/stsd.go, mp4/traf.go, mp4/traf_test.go, mp4/trak.go, mp4/trun.go, mp4/uuid.go, mp4/uuid_test.go, mp4/visualsampleentry.go
Add boxes uuid boxes for SmoothStreaming Tfxd and Tfrf boxes.
Make children of container boxes public.
Make trun Samples public, so that they can be changed.
Updated README.md with some warnings on direct changes of values.
=> Tfxd and Tfrf boxes for MSS. Made some attributes public.

mp4/mvhd.go, mp4/slicewriter.go, mp4/tkhd.go
=> Correct unity matrix in mvhd and tkhd

COPYRIGHT.md, LICENSE.txt, README.md
To get badge with right license.
=> Clean license file

mp4/box.go, mp4/stpp.go, mp4/stpp_test.go, mp4/subs.go, mp4/subs_test.go
stpp box + subs box for possible subsample information (for image subtitles)
=> stpp subtitle boxes

mp4/box.go, mp4/file.go, mp4/mediasegment.go, mp4/sidx.go, mp4/sidx_test.go
Added Segment Index Box. Useful for DASH OnDemand assets.
=> sidx box added

mp4/btrt.go, mp4/btrt_test.go, mp4/ctts_test.go, mp4/dref_test.go, mp4/elng_test.go, mp4/elst_test.go, mp4/emsg_test.go, mp4/ftyp_test.go, mp4/hdlr.go, mp4/hdlr_test.go, mp4/mdhd_test.go, mp4/prft.go, mp4/prft_test.go, mp4/sidx_test.go, mp4/stpp_test.go, mp4/stsc_test.go, mp4/subs_test.go, mp4/test_helpers.go, mp4/unknown_test.go, mp4/url_test.go, mp4/vmhd_test.go, mp4/wvtt_test.go
Checks that boxes can be encoded and decoded.
=> Add encode-decode tests for many boxes

bits/bits.go, bits/ebsp.go, bits/esbp_test.go, cmd/mp4ff-pslister/main.go, mp4/avc.go, mp4/avc_test.go, mp4/avcdecoderconfigurationrecord.go, mp4/initsegment.go
Parsing of all part of SPS and store in struct. Faciliates comparisons of different SPS
=> Full AVC SPS parsing

avc/avcdecoderconfigurationrecord.go, cmd/mp4ff-pslister/main.go, examples/initcreator/main.go, examples/resegmenter/resegment.go, go.mod, go.sum, mp4/box.go, mp4/file.go, mp4/fragment.go, mp4/mediasegment.go
Removed essentially all logging from libraries and the general dependency on external log library.
=> fix: remove non-standard log

README.md, Versions.md, avc/avc.go, avc/avcdecoderconfigurationrecord.go, avc/sps.go, bits/bits.go, bits/ebsp.go, bits/ebsp_test.go, bits/ebsp_writer.go, examples/initcreator/main.go, mp4/avcc.go, mp4/initsegment.go, mp4/initsegment_test.go
Support for multiple SPS
More explicit NALU types
Bug fixes
=> AVC improvements

examples/segmenter/segment.go, mp4/box.go, mp4/container.go, mp4/fragment.go, mp4/mdat.go, mp4/mdat_test.go, mp4/moof.go
Explicitly control if mdat shall use 64-bit largesize 64.
=> Can set mdat to use 64-bit largesize

mp4/sample.go, mp4/sampleflags.go, mp4/sampleflags_test.go, mp4/testdata/golden_1_frag_m4s_dump.txt, mp4/testdata/golden_1_m4s_dump.txt, mp4/testdata/golden_init_cenc_cmfv_dump.txt, mp4/testdata/golden_init_video_mp4_dump.txt, mp4/testdata/golden_moof_enc_m4s_dump.txt, mp4/testdata/golden_trun_dump.txt, mp4/trex.go, mp4/trun.go
Added interpreted sample flags output to Info for trex and trun.
=> Interpretation of sample flags in Info output

mp4/audiosamplentry.go, mp4/esds.go, mp4/mehd.go, mp4/mvhd.go, mp4/stbl.go, mp4/testdata/golden_init_cenc_cmfv_dump.txt, mp4/testdata/golden_init_prog_mp4_dump.txt, mp4/testdata/golden_init_video_mp4_dump.txt, mp4/visualsampleentry.go
Info layout and information
More pointers in StblBox
=> Minor fixes

aac/aac.go, aac/aac_test.go, aac/adts.go, aac/adts_test.go, bits/aereader.go, bits/aereader_test.go, examples/initcreator/main.go, mp4/initsegment.go
Support for ADTS headers decode and encode.
Mooved aac to own package
=> ADTS header functions

avc/avcdecoderconfigurationrecord.go, avc/sps.go, mp4/avcc.go, mp4/container.go, mp4/dref.go, mp4/initsegment.go, mp4/initsegment_test.go, mp4/stsd.go, mp4/visualsampleentry.go
Replaced a number of panic calls with error returns
=> AVCDecoderConfigurationRecord update

README.md, Versions.md, examples/segmenter/segment.go, mp4/ctts.go, mp4/stsc.go, mp4/stss.go, mp4/stts.go, mp4/testdata/golden_1_frag_m4s_dump.txt, mp4/tfhd.go
Fix/clarification of segment number offset to start at 1
Detailed tfhd Info for defaultSampleFlags
=> Bug fix version 0.16.2

bits/slicereader.go, hevc/doc.go, hevc/hevcdecoderconfigurationrecord.go, hevc/sps.go, mp4/hvcc.go, mp4/hvcc_test.go
Fix encoding and parsing of HEVCDecoderConfigurationRecord.
Tested via mp4/hvcc_test.go
=> Fix HEVCDecoderConfigurationRecord 

examples/initcreator/main.go, examples/multitrack/multitrack_test.go, examples/resegmenter/main.go, examples/segmenter/main.go, examples/segmenter/segment.go, hevc/sps.go, hevc/sps_test.go, mp4/file.go, mp4/initsegment.go, mp4/mediasegment_test.go, mp4/testdata/golden_init_cenc_cmfv_dump.txt, mp4/testdata/golden_init_prog_mp4_dump.txt, mp4/testdata/golden_init_video_mp4_dump.txt, mp4/visualsampleentry.go
Add more convenience functions for HEVC handling.
New methodImageSize for hevc.SPS
Fixed bug in resegmenter example code
=> Add HEVC handling to example code

cmd/mp4ff-nallister/main.go, cmd/mp4ff-wvttlister/main.go, examples/segmenter/segment.go, mp4/box.go, mp4/co64.go, mp4/co64_test.go, mp4/stbl.go
Large Chunk Offset box with 64 bit offset to complement the 32-bit stco box.
=> feat: add co64 box

avc/mime.go, avc/sps.go, hevc/mime.go, hevc/mime_test.go
Generate AVC and HEVC codec string from SPS
=> AVC and HEVC codec string generation

mp4/fragment.go, mp4/sampleinterval.go, mp4/trun.go, mp4/trun_test.go
SampleInterval collects Sample data together with contiguous mdat Data or indexes in lazy mdat.
Together with other new functions, this allows for more efficient ways to extract and add intervals
of samples without the need to extract mdat data sample by sample.
=> New structure SampleInterval

examples/initcreator/main.go, mp4/initsegment.go, mp4/stpp.go, mp4/stpp_test.go
* feat: new trak methods to set wvtt and stpp descriptors
* fix: make schemaLocation and auxiliaryMimeTypes optional in stpp box
=> Subtitle improvements

Makefile, avc/avc.go, avc/avc_test.go, hevc/hevc.go, hevc/hevc_test.go, mp4/traf.go, mp4/trun.go, mp4/trun_test.go
* Full control over firstSampleFlags in TrunBox
* More efficient checks for parameter sets in AVC and HEVC
* Added tests to HEVC nalu parsing
* Minor changes to Makefile
=> firstSampleFlags and avc/hevc parameter set checks

mp4/mdhd.go, mp4/mvhd.go, mp4/testdata/golden_init_cenc_cmfv_dump.txt, mp4/testdata/golden_init_prog_mp4_dump.txt, mp4/testdata/golden_init_video_mp4_dump.txt, mp4/tkhd.go
Add more information in mp4ff-info output:
* duration for tkhd
* creation and modification time for mvhd, tkhd, and mdhd
=> mp4ff-info times

Versions.md, mp4/version.go
New version 0.26.0:
* New example code `decrypt-cenc` for decrypting segment
* New tool `mp4ff-crop` for cropping mp4 file
* SEI parsing for H.264
* Interpret timestamps  in mvhd, tkhd, and mdhd
=> Version v0.26.0

mp4/stsz.go, mp4/stsz_test.go
=> fix: stsz size for uniform sample size

mp4/traf.go, mp4/trun.go, mp4/trun_test.go
In my use-case (boxing raw h264 streams), it's very useful to be able to control the TRUN flags as I don't find I need all of the entry flags in my output `.m4s` file.
Thanks a lot for the continued work on this library! It's been very useful :)
=> Expose Trun box flags

README.md, cmd/mp4ff-nallister/main.go, cmd/mp4ff-pslister/main.go, hevc/mime_test.go
New features:
* pslister output codecs string  for AVC and HEVC
* nallister supports input in bytestream (Annex B) format
=> Improvements to pslister and nallister

README.md, bits/aebyteswriter.go, bits/aereader.go, bits/fixedslicewriter.go, bits/fixedslicewriter_test.go, bits/slicewriter.go, examples/segmenter/main.go, examples/segmenter/segmenter.go, mp4/audiosamplentry.go, mp4/box.go, mp4/boxsr.go, mp4/dac3.go, mp4/dac3_test.go, mp4/dec3.go, mp4/dec3_test.go, mp4/stsd.go
Support ac-3 and and ec-3 in stsd and dac3/dec3 boxes including interpretation of channel maps.
Extended AccErrReader and SliceWriter with new methods for more efficient handling of the dac3 and dec3 boxes.
=> AC-3/Enhanced AC-3 support

mp4/stbl.go
The stbl.Sdtp short cut was not set.
=> fix: sdtp short cut

examples/initcreator/main.go, go.mod, go.sum, mp4/dec3.go, mp4/initsegment.go
* Add example code for generating init-segments for AC-3 and EC-3.
* More information in dec3.Info() output
=> Extend ac3 code

mp4/visualsampleentry.go
Some players want to have the parameter sets in the visual sample entry.
Methods are added to for conversion to such formats for AVC and HEVC.
hev1 -> hvc1 an…d avc3 -> avc1
=> feat: visual sample entry conversions

avc/avcdecoderconfigurationrecord.go, avc/pps.go, avc/sps.go, bits/aeebspreader.go, hevc/sps.go, hevc/sps_test.go
Extended parsing of HEVC SPS to include more complex field and Visual Usability Information (VUI).
Parsing of VUI was discussed in #119 
Some of the interesting information in VUI is sample aspect ratio and timing information.
=> Parse full HEVC SPS including VUI

examples/decrypt-cenc/main.go
=> fix: decrypt-cenc cli options

mp4/box.go, mp4/meta.go, mp4/mfra.go, mp4/minf.go, mp4/moof.go, mp4/moov.go, mp4/mvex.go, mp4/schi.go, mp4/sinf.go, mp4/stbl.go, mp4/traf.go, mp4/trak.go, mp4/visualsampleentry.go
Improvement as suggested in #160
=> Refactor: change string switch to type switch for AddChild

avc/annexb.go, avc/annexb_test.go, hevc/annexb.go, hevc/annexb_test.go
New functions to extract parameter sets for both AVC and HEVC from Annex-B bytestreams.
=> Parameter set extraction from byte streams

mp4/esds.go, mp4/esds_test.go
=> doc: better error message from esds

hevc/hevcdecoderconfigurationrecord.go, hevc/hevcdecoderconfigurationrecord_test.go
Bug fix from #173 and a simple test to make sure that it fixes the problem.
=> Fix hevc nalu arrays

hevc/hevcdecoderconfigurationrecord.go
=> NaluArray.Nalus no assignment

.github/workflows/go.yml, mp4/sampleinterval.go
Update higher version to 1.19. Now testing 1.13 and 1.19.
=> test: update Go version in github tests

bits/ebsp_test.go, bits/ebsp_writer.go
Fix reset of zero-counter in EBSPWriter
=> Fix EBSPWriter

sei/sei136.go, sei/sei_test.go
Changed attributes to public for third-party access and possibility to change the values.
=> Made SEI message type 136 attributes public

bits/ebsp_writer.go, sei/sei.go, sei/sei_test.go
Write SEI messages in EBSP format with startcode emulation prevention bytes inserted.
=> feat: add write SEI messages

bits/ebsp_writer.go
Fix infinite loop introduced in #182
=> fix: repair new WriteSEI function

mp4/file.go, mp4/file_test.go
Use a work slice to buffer data to avoid extra allocations when copying sample data to writer.
=> Optimize file.CopySampleData

cmd/mp4ff-crop/main.go, cmd/mp4ff-crop/stblcrop.go, mp4/file.go, mp4/stsc.go, mp4/stsc_test.go
Big performance improvements of file.CopySampleData and StscBox lookup methods. For the latter, additional data about the first sample in each stsc entry has been added. The API changes hit mp4ff-crop, which has been updated.
=> Optimize read of progressive files

README.md, mp4/file.go, mp4/file_test.go
Minor changes to comments, README and to tests.
=> Minor refactor/clarifications

mp4/prft.go
The fix for #198 issue has already been directly pushed to master branch. This is a small correction.
=> fix info for prft

README.md, cmd/mp4ff-nallister/main.go, hevc/sps.go, mp4/moov.go
Fix link to License file and a few typos.
=> License link fix

hevc/hevcdecoderconfigurationrecord_test.go, hevc/sps.go, hevc/sps_test.go
Add missing HEVC SPS parsing flag that signals scaling list data.
Added tests to confirm that new parsing works.
=> Fix HEVC SPS scaling list parsing

Versions.md, mp4/version.go
Bug fix version:
* Add missing parsing of `sps_scaling_list_data_present_flag` in HEVC SPS
=> Version 0.33.1

Versions.md, mp4/box.go, mp4/boxsr.go, mp4/mdat.go, mp4/version.go
- restore parsing behavior for non-complete mdat
=> Version 0.33.2

README.md
This PR adds Eyevinn support and service offerings to readme
=> chore(docs): added support and services section

CHANGELOG.md, Makefile, bits/fixedslicereader.go, bits/fixedslicereader_test.go, mp4/helpers_test.go, mp4/prft_test.go, mp4/saio_test.go, mp4/stpp.go, mp4/uuid_test.go, mp4/visualsampleentry.go
Towards better test coverage:
make coverage now outputs: 71.4% instead of 67.4%
Details of coverage can be seen in the file coverage.html generated by "make coverage".
Due to new tests, found two bugs in FixedSliceReader that have been fixed.
=> Better test coverage and bug fixes in FixedSliceReader

CHANGELOG.md, mp4/version.go
- Only start new segment at start or styp box
=> version v0.34.1

CHANGELOG.md, avc/slice.go, avc/slice_test.go, bits/aeebspreader.go, bits/aeebspreader_test.go
The AVC slice calculation was one off as reported in #232.
Fixes #232
=> Fix avc slice size

hevc/pps.go, hevc/pps_test.go
Sorry for PR spam. As always, i'm messed up with rebase and totally broke local branch.
I make all the changes you mention in https://github.com/Eyevinn/mp4ff/pull/230 and rebuild branch . Please check.
=> HEVC PPS parser revisited

CHANGELOG.md, cmd/mp4ff-pslister/main.go, hevc/pps_test.go
- `mp4ff-pslister` now provides PPS details for HEVC
- `mp4ff-pslister` now extracts inband parameter sets in progressive mp4 files
-  more tests for HEVC PPS parsing
=> Add hevc pps info

mp4/audiosamplentry.go
Good day!
This PR resolves issue #241 .
=> Add SetType method for AudioSampleEntryBox

CHANGELOG.md, hevc/sps.go
=> fix: hevc sps discard read

CHANGELOG.md
- Pointer to stpp sample entry in StsdBox
- Doc strings for pointers in StsdBox
- discard of parsing HEVC SPS data
- `SttsBox.GetSampleNrAtTime` now supports a final zero sample duration
=> Update CHANGELOG for v0.37.0

CHANGELOG.md
- Loudness boxes `ludt`, `tlou`, and `alou`
- Description boxes `desc`, `©cpy`, `©nam`, `©ART` boxes
- `GenericContainerBox` struct
- new `DecFileFlags` provide option to `DecodeFile` to look for mfra box
- Made `©too` use `GenericContainerBox`
- SidxBox got new attribute `AnchorPoint`
- DecodeFile uses sidx or mfra data to find segment boundaries
=> CHANGELOG for v0.38.0

CHANGELOG.md, cmd/mp4ff-crop/main.go, cmd/mp4ff-crop/stblcrop.go, cmd/mp4ff-crop/stblcrop_test.go
- mp4crop now crops elst entries
- mp4crop now handles multiple sample durations correctly
=> Fix mp4crop

av1/av1codecconfigurationrecord.go, av1/av1codecconfigurationrecord_test.go, av1/doc.go, mp4/av1c.go, mp4/box.go, mp4/boxsr.go, mp4/visualsampleentry.go
resolves #273 
I'm not sure if parsing OBUs should also be implemented in this pr.
=> feat: add av01 and av1C box

CHANGELOG.md, cmd/mp4ff-nallister/main.go, sei/sei1.go, sei/sei_test.go
New test and support in mp4ff-nallister for AVC SEI PicTiming
=> Handle avc pictiming with cbpDbpDelay present

CHANGELOG.md, mp4/doc.go, mp4/version.go
- Test of AVC PicTiming SEI with cbpDbpDelay set
- mp4ff-nallister has nicer output for annexb streams
- mp4ff-nallister handles AVC PicTiming SEI with cbpDbpDelay set
=> docs: update to v0.40.2

CHANGELOG.md, bits/aereader.go, bits/aereader_test.go, sei/sei.go, sei/sei1.go, sei/sei_test.go
=> fix: correct AVC PicTiming SEI offset

cmd/mp4ff-decrypt/main.go
=> fix: removed dead code in mp4ff-decrypt

CHANGELOG.md, mp4/version.go
- Support for decrypting PIFF-encrypted segments
- Parsing of AVCDecoderConfigurationRecord
- Parsing of time offset in AVC PicTiming SEI
- Set senc.perSampleIVSize properly
=> docs: v0.41.0

mp4/crypto.go, mp4/crypto_test.go
=> fix: pssh box extraction in DecryptInit

CHANGELOG.md, mp4/box.go, mp4/boxsr.go, mp4/coll.go, mp4/coll_test.go, mp4/helpers_test.go, mp4/smdm.go, mp4/smdm_test.go, mp4/visualsampleentry.go, mp4/vppc.go
Added support for SmDm and CoLL boxes defined for Webm (VP9) video codec
in https://www.webmproject.org/vp9/mp4/
=> SmDm and CoLL box support

mp4/traf.go, mp4/traf_test.go
Added tests to #421.
This features also resolves the issue #422.
=> Remove more encrypted boxes (#421 with tests)

Dockerfile.osc, README.md, docker/s3-entrypoint.sh
This PR makes the mp4ff commands available as a service in [Eyevinn Open Source Cloud](https://app.osaas.io/dashboard/service/eyevinn-mp4ff).
=> Enable mp4ff commands as a service in Open Source Cloud

mp4/sampleflags.go
Modifications for non-sync samples
=> non-sync sample
