Eyevinn/mp4ff

.gitignore, bits/bits_benchmark_test.go, cmd/mp4ff-pslister/main.go, mp4/audiosampleentry_test.go, mp4/audiosamplentry.go, mp4/avc.go, mp4/avcc.go, mp4/avcdecoderconfigurationrecord.go, mp4/box.go, mp4/btrt.go, mp4/elng.go, mp4/elng_test.go, mp4/esds.go, mp4/esds_test.go, mp4/file.go, mp4/fragment.go, mp4/initsegment_test.go, mp4/mdat_test.go, mp4/mediasegment_test.go, mp4/mvhd_test.go, mp4/tfdt_test.go, mp4/tfhd_test.go, mp4/tkhd_test.go, mp4/trun.go, mp4/url.go, mp4/visualsampleentry.go
```
bits/bits_benchmark_test.go:12:15: Error return value of `writer.Write` is not checked (errcheck)
writer.Write(0xff, 8)
^
mp4/avc.go:28:6: `isVideoNalu` is unused (deadcode)
func isVideoNalu(b []byte) bool {
^
mp4/box.go:191:6: `fixed16` is unused (deadcode)
func fixed16(bytes []byte) Fixed16 {
^
mp4/box.go:195:6: `putFixed16` is unused (deadcode)
func putFixed16(bytes []byte, i Fixed16) {
^
mp4/box.go:206:6: `fixed32` is unused (deadcode)
func fixed32(bytes []byte) Fixed32 {
^
mp4/box.go:210:6: `putFixed32` is unused (deadcode)
func putFixed32(bytes []byte, i Fixed32) {
^
mp4/trun.go:21:7: `dataOffsetPresentFlag` is unused (deadcode)
const dataOffsetPresentFlag = 0x01
^
mp4/audiosampleentry_test.go:14:12: Error return value of `ase.Encode` is not checked (errcheck)
ase.Encode(&buf)
^ …
```
=> Fix golangci-lint errors/warnings

README.md, examples/initcreator/main.go, examples/resegmenter/main.go, examples/resegmenter/resegment.go, examples/segmenter/main.go, examples/segmenter/segment.go, mp4/README.md, mp4/doc.go, mp4/file.go, mp4/fragment.go, mp4/initsegment.go, mp4/mdhd.go, mp4/mediasegment.go, mp4/moof.go, mp4/mvhd.go, mp4/sample.go, mp4/tkhd.go, mp4/traf.go, mp4/trak.go, mp4/trun.go
Enhanced documentation on sample data, time scales, and some checks that multiple tracks are not used in media tracks, since not supported.
Triggered by issue #8.
Changed SampleComplete PresentationTime into a method.
Also renamed SampleComplete to FullSample and some other API changes.
=> Better documentation of time scales and focus on single tracks

mp4/avcc.go, mp4/avcdecoderconfigurationrecord.go
Accept AvcC box with AVCDecoderConfigurationRecord lacking last bytes of configuration although AVCProfileIndication says that is should be there.
=> Handle parsing of broken AVCDecoderConfigurationRecord

README.md, avc/avc.go, avc/avc_test.go, avc/avcdecoderconfig_test.go, avc/avcdecoderconfigurationrecord.go, avc/slice.go, avc/slice_test.go, cmd/mp4ff-pslister/main.go, mp4/avcc.go, mp4/initsegment.go, mp4/initsegment_test.go
AVC parsing and types in separate package to prepare for HEVC addition at later stage.
Allows for simpler names without AVC.
Also added Slice type parsing.
=> Move avc code to own package

examples/segmenter/main.go, examples/segmenter/segment.go
mdat has all data in a slice, so the samples should be read from mdat.
In the future, we may have a lazy mdat that reads on request.
=> Fix of segmenter example to read samples from mdat

hevc/hevcdecoderconfigurationrecord.go
I was trying out `mp4ff-nallister` with an HEVC file and was getting some weird results. This seems to produced more sensical output.
=> Fix HEVCDecConfRec Size()

mp4/file.go, mp4/fragment.go, mp4/free_test.go, mp4/mediasegment.go, mp4/mediasegment_test.go, mp4/sgpd.go, mp4/traf.go, mp4/trun.go
Fix: The trun-tfhd optimization did not check if values have already been moved to tfhd.
Fix: Propagation of verbatim (non-optimized trun-tfhd) encoding for fragmented files.
=> Fix for trun optimize

Versions.md, cmd/mp4ff-pslister/main.go
mp4ff-pslister can now parse SPS without PPS.
For hex input, verbose output is on by default.
=> feat: mp4ff-pslister for sps only

mp4/sinf.go
The incorrect four-cc value was provided, leading to the `Children` still being populated, but the helper accessor is left unpopulated.
=> Correct four-cc for Schema Information child box

mp4/hdlr.go, mp4/hdlr_test.go
Now handles cases where there is no null-termination in name string.
This is controlled via an attribute, so one can choose to encode without it.
To emphasize that it shall be there according to the spec, the parameter is called LacksNullTermination.
=> Allow hdlr lacking null-termination of name

README.md, examples/multitrack/multitrack_test.go, mp4/file.go, mp4/fragment.go, mp4/mediasegment.go, mp4/mediasegment_test.go
Triggered by PR #76, this is a new way with three options for encoding a fragmented mp4.File:
EncodeModeTrunOptimize  = FragFileEncodeMode(0) // Optimize trun for size. May result in smaller encoded file
EncodeModeSegmentVerbatim = FragFileEncodeMode(1) // Encode boxes that are part of Init and MediaSegments
EncodeModeFileVerbatim  = FragFileEncodeMode(2) // Encode all boxes in file tree. Should reproduce a decoded file
Currently, the default mode is the first (EncodeModeTrunOptimize).
=> Change/refactor: Replace file.EncodeVerbatim with more options

mp4/stss.go, mp4/stss_test.go
Make stss.IsSyncSample() thread safe by changing creation of a map to a binary search.
Has the advantage that it works if the list of sync samples gets updated.
Solves #83.
=> fix: make IsSyncSample thread safe

mp4/box.go, mp4/file.go, mp4/file_test.go, mp4/mdat.go, mp4/mdat_test.go
- Add fileDecMode to mp4.File 
- Use functional options to set up decode and encode modes. 
- Remove `DecodeFileLazily` func 
The PR also includes:
- Changes in mdat.go 
- Add `AddReadSeeker` method to MdatBox. This method adds a necessary readseeker to MdatBox to read Mdat data when the file is decoded lazily.
- Add `ReadData` method to MdatBox to read data 
- if `decLazyDataSize` is greater than 0, which means the file is decoded lazily, so a readseeker is needed to retrieve data. 
- otherwise, Mdat data is in memory and can be retrieved directly.
=> Add fileDecMode to mp4.File

cmd/mp4ff-info/main.go, mp4/box.go, mp4/file.go, mp4/file_test.go, mp4/mdat.go, mp4/mdat_test.go
One can now parse a file and leave mdat for later.
When reading later, a readSeeker is needed.
mp4ff-info has been optimized to take advantage of this.
=> feat: lazy mdat decoding option

mp4/file.go, mp4/mediasegment_test.go
Fixing bug that was introduced in v0.23.0 with encoding modes.
Encode of segmented files without optimization did not give any output.
=> fix: encode non-optimized segment in EncModeSegment and broken test

mp4/stts.go, mp4/stts_test.go
Got an example of a surveillance video as a progressive mp4 file with variable frame rate in #94.
The SttsBox could not handle that, but that is now fixed.
=> fix: stts handling of variable sample duration

mp4/ctts.go, mp4/ctts_test.go, mp4/stts.go, mp4/stts_test.go
Fix algorithm in GetDecodeTime to return correct values as verified by tests provided in #100.
Also change log of zero sampleNr argument into panic, since that should be a programmatic error, rather than a parsing error.
=> Fix stts GetDecodeTime

mp4/initsegment_test.go, mp4/sidx.go, mp4/stsc.go, mp4/stsc_test.go
Make storage of data more efficient in stsc box.
This is in particular important for cases with big progressive files with very short (e.g. 1-frame) chunks.
=> More efficient data storage for stsc box

Makefile, cmd/mp4ff-nallister/main.go, cmd/mp4ff-wvttlister/main.go, examples/multitrack/main.go, examples/resegmenter/resegment.go, examples/segmenter/segmenter.go, mp4/fragment.go, mp4/hdlr.go, mp4/initsegment.go, mp4/sample.go, mp4/traf_test.go, mp4/trun.go
Change of API in GetSamples and GetFullSamples to return slices of samples instead of slices of pointers.
This means some more data copying, but less garbage collection.
Added new methods to add multiple samples AddSamples.
Improved Makefile: run `make all` and it will run tests, build commands, and run golangci-lint.
Added new init segment creation for `text/wvtt`.
=> Remove sample pointers

README.md, Versions.md, mp4/README.md, mp4/version.go
* Size() methods to InitSegment, Fragment and MediaSegment
* Improvements to ctts and stts boxes
* Slices of samples and fullsamples 
* Create init segments for wvtt and stpp
* Changed sample slices to remove pointers
* SampleIntervals for more efficient transformation of segments
* Spell out compositionTimeOffset instead of cto
* More efficient code to check for AVC and HEVC parameter sets
=> Version 0.25.0

avc/sei.go, avc/sei_test.go, avc/sps.go, bits/aeebspreader.go, bits/aereader.go, bits/aereader_test.go, cmd/mp4ff-nallister/main.go
Add support for parsing and interpreting SEI NAL units for AVC (but may work for HEVC as well).
There is general SEI parsing to just get the type and payload, and specific parsing
for type 4 (registered) and 5 (unregistered).
For registered, CEA-708 is detected and CEA-608 caption data is extracted.
Support for viewing this information is added to `mp4ff-nallister` with a new `-sei` option.
=> feat: SEI parsing for AVC and new SEI option in mp4ff-nallister

README.md, cmd/mp4ff-crop/byteranges.go, cmd/mp4ff-crop/crop_test.go, cmd/mp4ff-crop/main.go, cmd/mp4ff-crop/stblcrop.go, mp4/stsc.go
New tool to crop progressive mp4 files by only keeping the first N milliseconds of all tracks in the file, while leaving all the box structure intact and the interleaving intact. The actual duration being cropped depends on sync samples in the first video track, or on the audio samples if no video track is present.
A use case is generation of short versions of test content, while keeping the exact box structure of the original, except that
the mdat box is moved to the end.
=> New tool: mp4ff-crop

examples/segmenter/segmenter.go, mp4/box.go, mp4/mdat.go, mp4/moof.go, mp4/moov.go
Currently, it is assumed that `io.Reader` will fill the buffer, but [Go's
interface documentation](https://github.com/golang/go/blob/851ecea4cc99ab276109493477b2c7e30c253ea8/src/io/io.go#L60-L61) allows for incomplete reads. An example might be
a buffered network stream that only returns immediately available data.
Instead, `io.ReadFull` can be used to try to fill the given buffer.
=> Fix incomplete reads

avc/avcdecoderconfigurationrecord.go, examples/initcreator/main.go, hevc/hevcdecoderconfigurationrecord.go, hevc/hevcdecoderconfigurationrecord_test.go, mp4/avcc.go, mp4/hvcc.go, mp4/hvcc_test.go, mp4/initsegment.go, mp4/initsegment_test.go
One can now choose to include parameter sets in the avc3 and hev1 sample entries.
The hev1 sample entry is also no longer signaled complete.
=> Flexible video sample entries

mp4/uuid.go, mp4/uuid_test.go
Decode and encode UUIDBox with unknown UUID values.
This covers the case of parsing an unknown PIFF box reported in #146
=> fix: error instead of panic for unknown uuid

examples/segmenter/segmenter.go
This is an extension of the segmenter example to add the optional mehd box to to signal the duration of a segmented asset in the moov box. Does not solve #152.
=> Extend segment example to insert mehd box

cmd/mp4ff-nallister/main.go
Example output:
1. Print single sample:
```
> mp4ff-nallister -c "hevc" -m 1 asset_with_video_track.cmfv
Sample 1, pts=7200 (211B): AUD_35 (3B), VPS_32 (24B), SPS_33 (45B), PPS_34 (7B), RAP_IDR_20 (112B)
```
2. Print single sample with an extra 112 raw bytes of each NAL unit
```
> mp4ff-nallister -c "hevc" -m 1 -raw 112 asset_with_video_track.cmfv
Sample 1, pts=7200 (211B):
AUD_35 (3B) raw: 460150,
VPS_32 (24B) raw: 40010c01ffff016000000300900000030000030078959809,
SPS_33 (45B) raw: 420101016000000300900000030000030078a00502016965959a4932bc05a80808082000000300200000030321,
PPS_34 (7B) raw: 4401c172b46240,
RAP_IDR_20 (112B) raw: 2801af11316ce63170f49300bfff41985cf2277637ca1905205a942000003120a8b04641a42227d00000030000ba80930af2180000030000030003ae87000003000003000003001050000003000003000003 …
```
=> [mp4ff-nallister] Add a new option to print raw bytes of NAL units

cmd/mp4ff-crop/stblcrop.go, mp4/ctts.go, mp4/ctts_test.go
Looking up ctts values for files with many chunks was very slow because of cumulative linear search.
Is now rewritten using binary search and a better internal data structure.
=> Optimize ctts value retrieval

aac/aac.go, mp4/fragment.go, mp4/tfdt.go, mp4/tfdt_test.go
Changed BaseMediaDecodeTime of TfdtBox to have a setter that sets the version flag properly.
There was a bug in `AddSampleInterval` where the flag was not properly set.
=> Fix stricter tfdt time setting

avc/annexb.go, avc/annexb_test.go, hevc/annexb.go, hevc/annexb_test.go
New methods for both AVC and HEVC to extract NALUs of specific types from bytestreams.
=> NALU extraction from byte streams

Versions.md, mp4/file.go, mp4/file_test.go, mp4/version.go
Fixes copy sample condition in v0.30.0. Optimization not running as workSpace size > 0 and infinite loop when size == 0.
=> v0.30.1 bug fix release

aac/adts.go, aac/adts_test.go
Parse the two extra CRC bytes in ADTS header if present.
Also provide HeaderLength as a new attribute.
=> fix: add adts crc parsing

Versions.md, mp4/version.go
- Support multiple sidx
- Optimize stsc lookups.
- New return type for NewNaluArray. 
- Bug fixes in prft, adts and avc interlace.
- Covered by PRs 190-197, and 199
=> version 0.31.0

mp4/box.go, mp4/box_test.go
Add new function RemoveBoxDecoder that turns off decoding of a specific box type by deleting its mapping.
This makes it possible to get around problems with certain uninteresting box types.
A test with a malformed `meta` box was added to exemplify how this can be used.
=> feat: RemoveBoxDecoder makes it possible to make a specific box unknown

bits/fixedslicereader.go, bits/slicereader.go, mp4/box_test.go, mp4/meta.go, mp4/meta_test.go
The QuickTime meta atom differs from the MP4 meta box in that it does not have any version and flags bytes.
The QuickTime atom is defined in 
https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html
Another PR, #204, made it possible to avoid decoding boxes like the QuickTime meta box which would cause an error. This PR makes that particular box variation decodable, by looking ahead in the data to determine if a `hdlr` box is appearing directly after the  meta header. 
A new method has been introduced, MetaBox.IsQuickTime(), to check if the box is of QuickTime variety.
Decoding and Encoding QuickTime meta atoms is henceforth possible. To create a QuickTime meta atom from scratch is, however, not supported.
=> Add support for QuickTime meta atom (differs from MP4 meta box)

aac/adts.go, aac/adts_test.go
There are cases where it is not enough to look for the 12-bit ADTS start pattern 0xfff. This PR makes the search somewhat more robust by also looking at the two level bits and requesting that they are zero.
=> feat: Make ADTS parsing somewhat more robust

mp4/file.go
This code does nothing since `err` is not changed after the previous check three lines up
=> Remove unnecessary err check

CHANGELOG.md, mp4/version.go
- New function: `mp4.NewMediaSegmentWithStyp()`
- Associate emsg boxes with fragments
- New Fragment method: `AddEmsg()`
- `colr` box support
- CHANGELOG.md (this file) instead of Versions.md
- More tests
- Bugs in FixedSliceReader: ReadUint24 and LookAhead
- Optimized translation from Annex B (start-code separated) video byte streams into length-field
separated one
- Output of cenc example changed with styp boxes not included
- ADTS parsing somewhat more robust
- LastFragment() returns nil if no fragment in Segment
- Makefile target `coverage`
=> Version 0.34.0

CHANGELOG.md, mp4/stpp.go, mp4/stpp_test.go
The `schema_location` and `auxiliary_mime_types` are both optional utf8-lists in `stpp` box.
It was assumed that they were not present if empty, but #228 reported on a case where they are present but empty.
A careful reading of ISO/IEC 14496-12 reveals that the field should have. a single zero-termination byte, even if
not set. This now changed so that reading and writing is consistent.
Fixes #228.
=> Fix stpp empty utf-8 lists

hevc/sps.go
Good day!
This PR introduce parser for HEVC SPS extensions. 
Details:
- SccExtension is one of dependencies for the slice header parser. All other extensions done just because ;)
- Another dependency is LongTermRPS. Implemented struct have extra fields to reuse it in slice header parser.
- In the 3d extension i decided to put all fields in one struct and mark duplicated entries with suffix (0/1).
- SPS extensions now have prefix SPS to separate it from PPS extensions.
- Some slices initialised via make() to remove overhead on unnecessary calls to grow.
- SPS parser now correctly process final data and checks on trail bit.
=> HEVC SPS extensions parser

CHANGELOG.md, cmd/mp4ff-nallister/main.go, sei/sei.go, sei/sei_test.go
Introduced a specific error for the case where SEI NALUs lack the rbsp_trailing_bits byte.
Updatet mp4ff-nallister to handle this error by printing the data and an error message.
=> change: report ErrRbspTrailingBitsMissing when parsing SEI NALUs

CHANGELOG.md
- SEI NAL unit parser reports ErrRbspTrailingBitsMissing error together with NAL units
- mp4ff-nallister reports error and SEI data when `rbsp_trailing_bits` are missing
- AVC SPS HRD parameter name corrected to DpbOutputDelayLengthMinus1
- Add WriteFlag method to SliceWriter interface (present in FixedSliceWriter)
- Parsing of AVC SEI pic_timing with HRD parameters
- mp4ff-nallister handles AVC SEI pic_timing with HRD parameters if SPS is present
- fix error in TimeOffset output of SEI 136
- Support for SEI message 1 pic_timing for AVC
- Example `combine-segs` that shows how to multiplex init and media segments into multi-track segments
=> docs: update CHANGELOG for v0.36.0

CHANGELOG.md, mp4/stts.go, mp4/stts_test.go
This fixes `GetSampleNrAtTime()` to return the last sample number for the rather  odd case of having a final zero sample duration in the `stts` box.
This solves #259.
=> fix: handle stts case with single trailing zero duration

CHANGELOG.md, mp4/box.go, mp4/boxsr.go, mp4/container.go, mp4/ffmpeg.go
Quite a few boxes for metadata in QuickTime and ffmpeg have the structure of a ContainerBox wrapping an `data` box.
Therefore, a `GenericContainerBox` has been introduced and mapped to the boxes
```
desc
©cpy
©nam
©too
©ART
```
to it. It can also for other container boxes that don't want direct pointers to children.
The previous implementation of CTooBox has been removed.
=> feat: description boxes

CHANGELOG.md, mp4/file.go, mp4/file_test.go
Make mfro discovery robust.
Updated changelog for v0.38.1
Fixes #270
=> fix: make mfro search return silently if not present

mp4/fragment.go, mp4/trun.go
Cleaner count of samples by dropping internal sampleCount attribute.
=> refactor: only use trun.SampleCount() to get number of samples

mp4/uuid.go
In uuid.go there are already the UUID for Smooth Streaming Tfxd and Tfrf boxes defined. It makes sense to also add the UUID for Smooth Streaming StreamManifest and LiveServerManifest. This PR adds that. Also added references to the MSS Standard sections for all four UUID.
I'm unsure on the names, wdyt?
=> feat: add missing MSS UUID

CHANGELOG.md, avc/slice.go, avc/slice_test.go, avc/sps.go, bits/aeebspreader.go, bits/aeebspreader_test.go
Fix the size of AVC slice header parsed by fixing AVC ChromeArrayType to follow standard.
Also add new NrBitsRead method to AccErESBSPReader
=> Fix avc ChromeArrayType 

CHANGELOG.md, mp4/version.go
- New CLI app: mp4ff-encrypt to encrypt segments
- New CLI app: mp4ff-decrypt to decrypt segments
- New encyption-related functions in mp4
- GetAVCProtectRanges to fine protection ranges for AVC video
- CryptSampleCenc for encrypting of decrypting with cenc scheme
- EncryptSampleCbcs - for encrypting with cbcs scheme
- DecryptSampleCbcs - for decrypting with cbcs scheme
- InitProtect to protect an init segment
- EncryptFragment to encrypt a fragment
- DecryptInit to extract and remove  decryption info from an init segment
- DecryptFragment to decrypt a fragment
- ExtractInitProtect to generate data needed for encryption
- AccErrEBSPReader.NrBitsRead method
- PsshBoxesFromBase64 and PsshBoxesFromBytes functions
- SPS.ChromaArrayType method
- Makefile now builds all CLI applications with …
=> docs: update for v0.40.0

CHANGELOG.md, avc/avcdecoderconfigurationrecord.go
Fix the parsing of AVCDecoderConfigurationRecord to follow the spec in both parsing and size calculation.
=> Fix avc dec conf rec

CHANGELOG.md, mp4/pssh.go, mp4/pssh_test.go
Better handling of UUID in mp4 library.
Also detect W3C Common PSSH box UUID.
=> feat: add w3c common-pssh-box uuid + make uuid check case-insensitive

CHANGELOG.md, mp4/initsegment.go, mp4/initsegment_test.go
Live streams should not have an mehd box in the init segment.
This PR adds a method to remove such a box if present.
Replaces #323
=> feat: InitSegment.TweakSingleTrakLive to tweak init segments

CHANGELOG.md, mp4/stpp.go, mp4/stpp_test.go
Handle the case where there is not even an terminal zero bytes for optional utf8lists in stpp box.
=> fix: allow absent optional fields in stpp

CHANGELOG.md, mp4/file.go, mp4/mfro.go
The check for mfro box at end of file is now more robust by checking the header for the corresponding "mfro" type.
Added a new function TrypDecodeMfro().
=> fix: more careful mfro decoding

.github/workflows/go.yml, CHANGELOG.md, avc/slice_test.go, bits/reader.go, bits/writer_benchmark_test.go, cmd/mp4ff-decrypt/decrypt_test.go, cmd/mp4ff-encrypt/main.go, cmd/mp4ff-nallister/main.go, cmd/mp4ff-pslister/main.go, examples/combine-segs/main.go, examples/multitrack/helpers_test.go, examples/multitrack/multitrack_test.go, go.mod, go.sum, hevc/slice_test.go, mp4/benchmarks_srw_test.go, mp4/benchmarks_test.go, mp4/boxsr_test.go, mp4/dac3.go, mp4/dec3.go, mp4/file_test.go, mp4/infodumper_test.go, mp4/initsegment_test.go, mp4/mediasegment_test.go
Github actions no longer support testing with Go version 1.13
Update minimum version used in Github actions testing to 1.16.
Also removed the calls to the obsolete ioutil package
=> Update min go version to 1.16

CHANGELOG.md, mp4/descriptors.go, mp4/descriptors_test.go, mp4/esds.go, mp4/infodumper.go
As mentioned in #350, some mp4 samples in the wild have erroneous descriptors.
This PR extends the descriptor handling to become more general, but also to handle
and store data corresponding to bad descriptor data at the end of ES descriptor,
and DecoderConfig descriptor. This makes it possible to Decode and Encode such
assets without change of the data.
The Info() interface as used by mp4ff-info has been extended to reveal more information about encoders.
In particular, a higher level for `esds` boxes propagates into descriptors.
This should solve #350 and #348.
=> feat: handle bad descriptors and provide detailed info

CHANGELOG.md, bits/fixedslicereader.go, bits/fixedslicereader_test.go, bits/slicereader.go, mp4/descriptors.go, mp4/dref_test.go, mp4/testdata/golden_init_cenc_cmfv_dump.txt, mp4/testdata/golden_init_prog_mp4_dump.txt, mp4/testdata/golden_init_video_mp4_dump.txt, mp4/url.go, mp4/url_test.go
The URL box should have a zero-terminated location string, or no data.
This PR supports that the termination zero byte is missing and that there is a URL also when the content
has the flag set to indicate that it is self-contained.
Solves #353.
=> Improved url box parsing

CHANGELOG.md, mp4/version.go
- minimum Go version 1.16.
- ioutil imports replaced by io and os imports
- Info (mp4ff-info) output for esds boxes
- API of descriptors
- Parsing and info output for url boxes
- support for parsing of hierarchical sidx boxes
- handling of partially bad descriptors
- handle url boxes missing mandatory zero-ending byte
- support for ssix box
- support for leva box
- details of descriptors as Info outout (mp4ff-info)
=> docs: v0.45.0

mp4/stts.go
Hi all,
Because `SampleCount[i]` and `dur` are both uint32, so `SampleCount[i] * dur` will be casted into uint32 before the casting to uint64 take effect. Thus, with a long enough video, we will experience number overflow.
=> Fix Number overflow when getting sample DTS

CHANGELOG.md, mp4/box.go, mp4/boxsr.go
To facilitate trouble-shooting box decode errors now include start position of the box.
Should help a little in #245 and similar cases.
=> feat: add pos in decoder error messages

CHANGELOG.md, mp4/container.go, mp4/elng.go, mp4/elng_test.go
The `elng` box was errononously not reading/writing full box headers. This is now changed, but one can still read the old errononous type.
This should solve the re-opened issue #245 where the `moov` box could not be parsed.
=> fix: elng should be full box

CHANGELOG.md, mp4/audiosamplentry.go, mp4/stsd.go
All sample descriptors can have a Btrt box with bitrate information. This new method of `stsd` will return such a box if found in its (known children).
=> feat: GetBtrt method for StsdBox

CHANGELOG.md, mp4/traf.go
Issue #367 reports a problem with certain sbgp and sgpd types. The issue arises in combination with `senc` where the test for sbgp and sgpd types was too restrictive.
Fixes #367.
=> fix: allow other sbgp and sgpd types than seig with senc

CHANGELOG.md, mp4/descriptors.go, mp4/descriptors_test.go
The standard allows DecoderSpecificInfo to be absent as pointed out in #372.
This PR fixes this.
=> fix: allow missing optional DecoderSpecificInfo

CHANGELOG.md, mp4/boxsr.go, mp4/file.go, mp4/file_test.go
The mp4.File.Mdat box will no longer point to an empty mdat box if there is a non-empty one.
Multiple non-empty mdat boxes will generate an error.
Resolves #371
=> fix: allow additional empty mdat boxes in progressive files

CHANGELOG.md, mp4/file.go, mp4/fragment.go, mp4/sample.go
The two functions DumpWithSampleData and Fragment.DumpSampleData are too specific and should not have been part of the mp4ff repo.
No tests or programs used them.
=> change: remove too specific functions 

cmd/mp4ff-pslister/main.go, mp4/file_test.go, mp4/helpers_test.go, mp4/pssh_test.go
New linting issues reported after upgrading golangci-lint.
=> chore: fix new golangci-lint issues

mp4/samplegroupentries.go
Playground showcasing the parsing issue: https://go.dev/play/p/pJ_4OHqLP2R
Modulus operator on the second half of the byte lead to inaccurate values.
Fixes #381.
=> Modify SEIG parsing to handle skip / crypt block byte.

CHANGELOG.md, mp4/crypto.go, mp4/crypto_test.go
=> Fix decrypt re-encrypt segment

CHANGELOG.md, mp4/descriptors.go, mp4/esds.go, mp4/esds_test.go
Handle case when esds box is shorter because (the mandatory) SLConfig descriptor is not present.
Solves #393.
=> fix:  don't enforce minimal esds size

CHANGELOG.md, mp4/dac3.go, mp4/dac3_test.go
The dac3 box reported in #395 has four zero-valued bytes at the start of the payload.
This is not aligned with the spec, but is now parsed and can be written again.
Solves #395.
=> feat: support for weird dac3 reported in Issue #395

mp4/stsc.go, mp4/stsc_test.go
stsc did not write the first sample description ID value to correctly as a new value appeared.
Fixes #398.
=> fix: stsc correct handling of multiple sample description IDs

mp4/mime.go, mp4/testdata/fuzz/FuzzDecodeBox/77cf6e30648805ea
Fix the panic found by fuzzing:
```
--- FAIL: FuzzDecodeBox (478.19s)
--- FAIL: FuzzDecodeBox (0.00s)
testing.go:1591: panic: runtime error: index out of range [-1]
goroutine 4015806 [running]:
runtime/debug.Stack()
/opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/debug/stack.go:26 +0xc4
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1591 +0x21c
panic({0x1030bc1a0?, 0x1400a1521f8?})
/opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785 +0x124
github.com/Eyevinn/mp4ff/mp4.DecodeMimeSR({{0x1400a68e9e0?, 0x1400a6a3f20?}, 0x1400a68e9e0?, 0x8?}, 0x14009e8c658?, {0x1030df818, 0x1400a68cd40})
/Users/eric/src/mp4ff/mp4/mime.go:35 +0x214
github.com/Eyevinn/mp4ff/mp4.DecodeMime({{0x1400a68e9e0?, 0x140001207b0?}, 0x1400a68e9e0?, 0x4?}, 0x0, …
```
=> fix: ensure mime box is large enough to read

mp4/fuzz_test.go, mp4/ssix.go, mp4/testdata/fuzz/FuzzDecodeBox/6041c517bf46e9ee
Fix the memory usage found from fuzzing:
```
github.com/Eyevinn/mp4ff/mp4.DecodeSsixSR
/Users/eric/src/mp4ff/mp4/ssix.go
Total:     18.07GB    18.07GB (flat, cum) 99.76%
73            .          .           	subSegmentCount := sr.ReadUint32() 
74            .          .           	sizeLeft := hdr.Size - 16 
75            .          .           	if subSegmentCount > uint32(sizeLeft/8) { 
76            .          .           		return nil, fmt.Errorf("too many subsegments: %d", subSegmentCount) 
77            .          .           	} 
78      18.07GB    18.07GB           	b.SubSegments = make([]SubSegment, subSegmentCount) 
79            .          .           	for i := 0; i < int(subSegmentCount); i++ { 
80            .          .           		rangeCount := sr.ReadUint32() 
81            . …
```
=> fix: ensure ssix box is large enough to read

mp4/tfhd.go, mp4/traf.go
Hey,
I wanted to use these constants when I noticed they aren't actually exposed. This PR aims to export them in a similar manner like how it was done in trun's case:
https://github.com/Eyevinn/mp4ff/blob/5e414b1f5b54ef5147fe4c039df0b81975b98de2/mp4/trun.go#L22-L27
I wonder if there is a reason for these to be local in the first place.
PS: I hope the CI will let it pass without adding more test coverage as there isn't much to add here for extra testing. :relaxed:
=> feat: export TFHD flag constants for external use

CHANGELOG.md, avc/avcdecoderconfig_test.go, avc/avcdecoderconfigurationrecord.go
Replaces #420 with linter fixes and CHANGELOG update
=> Added skip bytes support to AVCDecoderConfigurationRecord
